# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Antonio Ivanovski | toteto
description: "Personal page and blog"
keywords: "antonio ivanovski, антонио ивановски, toteto, тотето, software engineer"
url: https://toteto.tech
baseurl: ""

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Antonio Ivanovski
  job: Software Engineer
  bio: "// TODO"
  thumb: /images/author.png
  email: me@toteto.tech
  url: https://toteto.tech
  github: https://github.com/toteto
  facebook: https://www.facebook.com/tote.bt
  instagram: https://www.instagram.com/antonioivanovski
  linkedin: https://www.linkedin.com/in/antonioivanovski

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude:
  [
    "config.rb",
    "src",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "README.md",
    "Rakefile",
  ]
